export const sample_foods = [
  {
    id: "1",
    name: "Pizza Pepperoni",
    cookTime: "10-20",
    price: 150,
    origins: ["italy"],
    imageUrl: "food-11.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "2",
    name: "Meatball",
    price: 60,
    cookTime: "20-30",
    origins: ["persia", "middle east", "china"],
    imageUrl: "food-22.jpg",
    tags: ["SlowFood", "Lunch"],
  },
  {
    id: "3",
    name: "Hamburger",
    price: 90,
    cookTime: "10-15",
    origins: ["germany", "us"],
    imageUrl: "food-33.jpg",
    tags: ["FastFood", "Hamburger"],
  },
  {
    id: "4",
    name: "Fried Potatoes",
    price: 40,
    cookTime: "15-20",
    origins: ["belgium", "france"],
    imageUrl: "food-44.jpg",
    tags: ["FastFood", "Fry"],
  },
  {
    id: "5",
    name: "Chicken Soup",
    price: 80,
    cookTime: "40-50",
    origins: ["india", "asia"],
    imageUrl: "food-55.jpg",
    tags: ["SlowFood", "Soup"],
  },
  {
    id: "6",
    name: "Vegetables Pizza",
    price: 120,
    cookTime: "40-50",
    origins: ["italy"],
    imageUrl: "food-66.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
];

export const sample_tags = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "SlowFood", count: 2 },
  { name: "Hamburger", count: 1 },
  { name: "Fry", count: 1 },
  { name: "Soup", count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: false,
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "jane@gmail.com",
    password: "12345",
    address: "Shanghaiii",
    isAdmin: true,
  },
  {
    id: 3,
    name: "Lucifer",
    email: "lucifer@gmail.com",
    password: "12341234",
    address: "Jeeva Nager, G.N.Mills, Coimbatore",
    isAdmin: true,
  },
];
